# Generated by Django 4.0.10 on 2023-11-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "wagtail_devtools_test",
            "0004_standardpageone_standardpagethree_standardpagetwo",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TestModelAdminThree",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="TestModelAdminTwo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
        ),
    ]
