# Generated by Django 4.0.10 on 2023-11-18 15:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_devtools_test", "0005_testmodeladminthree_testmodeladmintwo"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TestModelAdmin",
            new_name="TestModelAdminOne",
        ),
    ]
