# Generated by Django 4.0.10 on 2023-11-18 15:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wagtail_devtools_test", "0009_testsnippetthree_testsnippettwo"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TestSnippet",
            new_name="TestSnippetOne",
        ),
    ]
